name: Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        name: Setup cache
      - uses: actions/cache@v4
        name: Use cache
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync --frozen --group docs
        name: Install packages
      - run: uv add fastapi
        name: Install FastAPI
      - run: uv run python build_openapi.py
        name: Buidl API docs
      - run: uv run mkdocs gh-deploy --force
        name: Deploy
